name: rider_and_clerk_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  timeline_tile: ^2.0.0
  flutter_secure_storage: ^9.2.4
  firebase_core: ^3.10.1
  firebase_cloud_firestore: ^5.4.4
  firebase_messaging: ^15.2.1
  firebase_auth: ^5.4.1
  flutter_local_notifications: ^18.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_maps_flutter: ^2.10.0
  flutter_google_maps_webservices: ^1.1.1
  shared_preferences: ^2.5.2
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  firebase_database: ^11.3.2
  url_launcher: ^6.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Eina03
      fonts:
        - asset: assets/fonts/muli/Eina03.ttf
  

